### ISSUE TITLE
TypeError: cannot read property 'name' of null (interactive-supports-focus)

### ISSUE THREAD

**Issue by thetre97** [maranran/eslint-plugin-vue-a11y#16]
Similar to #14, I get the below when using v30, but not v28:

```
[Error - 21:21:31] TypeError: Cannot read property 'name' of null
Occurred while linting /media/***/manage/pages/products/create.vue:81
    at node.startTag.attributes.find.a (/media/***/manage/node_modules/eslint-plugin-vue-a11y/lib/utils/index.js:66:51)
    at Array.find (<anonymous>)
    at Object.getDirective (/media/***/manage/node_modules/eslint-plugin-vue-a11y/lib/utils/index.js:62:37)
    at Object.getAttribute (/media/***/manage/node_modules/eslint-plugin-vue-a11y/lib/utils/index.js:58:51)
    at EventEmitter.VElement (/media/***/manage/node_modules/eslint-plugin-vue-a11y/lib/rules/interactive-supports-focus.js:36:35)
    at EventEmitter.emit (events.js:187:15)
    at NodeEventGenerator.applySelector (/media/***/manage/node_modules/eslint-plugin-vue-a11y/node_modules/vue-eslint-parser/index.js:3273:26)
    at NodeEventGenerator.applySelectors (/media/***/manage/node_modules/eslint-plugin-vue-a11y/node_modules/vue-eslint-parser/index.js:3287:22)
    at NodeEventGenerator.enterNode (/media/***/manage/node_modules/eslint-plugin-vue-a11y/node_modules/vue-eslint-parser/index.js:3295:14)
    at traverse (/media/***/manage/node_modules/eslint-plugin-vue-a11y/node_modules/vue-eslint-parser/index.js:113:13)
```

It seems to be `interactive-supports-focus` this time...

**Comment by maranran** [comment]
fixed it in next version, thanks for your issue @thetre97
